version: '3'

services:
    postgres:
        image: postgres:13.2
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
            timeout: 45s
            interval: 10s
            retries: 10
        restart: always
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=password
          - APP_DB_USER=cinemaadmin
          - APP_DB_PASS=cinemaadmin
          - APP_DB_NAME=cinema
        volumes:
          - ./db:/docker-entrypoint-initdb.d/
        ports:
          - 5432:5432
